- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
Added:
- RegisterViewModel
- LoginViewModel
>  Login and Register ViewModels

- app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
- LoginActivity with loginViewModel, validation handling
- RegisterActivity with registerViewModel, validation handling
> Connecting viewModels with Activities

- app/build.gradle.kts
- app/src/test/java/com/example/reservant_mobile/ExampleUnitTest.kt
- app/src/test/java/com/example/reservant_mobile/LoginUnitTest.kt
- app/src/test/java/com/example/reservant_mobile/LoginViewModelUnitTest.kt
- app/src/test/java/com/example/reservant_mobile/RegisterViewModelUnitTest.kt
Add LoginVM and RegisterVM tests
> [FEATURE]MaciekM_add tests

- app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
Validation of
- signInValidation()
- registerValidation()
> Validation

- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/endpoints.xml
- app/src/main/res/values/regs.xml
- app/src/main/res/values/strings.xml
Zasoby:
* wsparcie języka polskiego
* końcówki (bez testów)
* regexy
> [FEATURE] add basic resources

- app/build.gradle.kts
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/LoginCredentialsDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RegisterUserDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/services/APIService.kt
- app/src/main/java/com/example/reservant_mobile/data/services/UserService.kt
Pozdrawiam wszystkich i miłego wieczoru :>
> [FEATURE]MaciekM add apiservice implementation

- app/src/androidTest/java/com/example/reservant_mobile/LoginActivityTest.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Added resources in LoginActivity, HomeActivity, RegisterActivity.
> [FEATURE] Update resources in Login, Home, Register activies

- app/src/androidTest/java/com/example/reservant_mobile/RegisterRestaurantActivityTest.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MainActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Added: 
- RegisterRestaurantActivity
- RestaurantTypeDropdown Composable
- InputUserFile Composable
[FIXED] BUG:
- Clicking on RestaurantTypeDropdown textArea not showing menu, only arrow works
> [FEATURE] RegisterRestaurantActivity

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RegisterUserDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/fields/FormField.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/fields/Result.kt
- app/src/main/java/com/example/reservant_mobile/data/services/UserService.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
no backend for this yet, so should test before merge
> [FEATURE] backend validation in register and login forms

- app/src/main/java/com/example/reservant_mobile/data/services/UserService.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/Endpoints.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
no backend for this yet, so should test before merge
> [FEATURE] check if login is unque

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/FileUploadDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RegisterRestaurantDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/TableDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/services/APIService.kt
- app/src/main/java/com/example/reservant_mobile/data/services/FileUploadService.kt
- app/src/main/java/com/example/reservant_mobile/data/services/RestaurantService.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/Endpoints.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
* FileUplaodService
* RestaurantService
> [FEATURE] MaciekM restaurant service

- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/Regex.kt
@Dzwiedzi wiesz jak w tym oknie dialogowym zmienić format daty?
> [REFACTORING] refactor date format

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantEmployeeDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantGroupDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/services/APIService.kt
- app/src/main/java/com/example/reservant_mobile/data/services/RestaurantService.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/Endpoints.kt
> [REFACTOR] restaurant service

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantMenuDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantMenuItemDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/services/RestaurantMenuService.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/Endpoints.kt
Basic zarządzanie menu i menu items
> [FEATURE]MaciekM restaurant menu service

- app/src/main/java/com/example/reservant_mobile/data/services/UserService.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/Roles.kt
> [FEATURE]MaciekM add global user info

- app/src/main/java/com/example/reservant_mobile/data/utils/BottomNavUtils.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantManagementViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
- Activity now displays restaurants depending on a selected group
- If user has only 1 group, there will be no option for choosing a group
> [FEATURE] RestaurantManagementActivity group support

- app/src/androidTest/java/com/example/reservant_mobile/RegisterRestaurantActivityTest.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantMenuDTO.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MenuManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/NavigationArguments.kt
- app/src/main/java/com/example/reservant_mobile/ui/constants/NavigationRoutes.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/MenuManagementViewModel.kt
- app/src/main/res/values/strings.xml
- navigacja do elementów listy
- usuwanie elementów
> [FEATURE] basic menu management

- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantManagementViewModel.kt
+ Changed the image to an icon in the IconWithHeader composable to support dark mode
+ Added logic for deleting a restaurant in RestaurantManagementActivity (currently commented out)
+ Implemented second-step validation which includes checking if files are in PDF format and verifying that mandatory files are uploaded
> [FEATURE] RestaurantManagementActivity / RegisterRestaurantActivity

- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantOwnerProfileActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Dodatkowo logout (w ramach testów)
> [FEATURE] MaciekM check restaurant owner

- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
also refactored countdown popup to use the new component
> [FEATURE] DeletePopup

- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
* animejszyn
* lista zamiast mapy
* fajniejsza nazwa
> [REFACTOR] MaciekM FloatingTabSwitch 2.0

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
https://github.com/Reservant-inc/reservant-mobile/pull/99
> [FEATURE] MaciekM bottom sheet

- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Added delete restaurant button logic in RestaurantManagementActivity with additional confirmation pop-up.
+ DELETE /my-restaurants/{id} doesnt work on backend, so PR should be verified after backend fix. 
(Reservant-inc/reservant-backend#98)
> [FEATURE] Delete restaurant w/ confirm pop-up

- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
+ Favourite button on right side, under main photo
+ Menu and Events in FloatingTabSwitch
+ Removed categories
+ Moved constants like gallery, menu to resource
+ Swapped delivery cost with restaurant type
!! [BUG] When swapping menu to events, photos from MenuItemCard lose its formatting
> [FEATURE] RestaurantDetail Refactor

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantDTO.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
+ Added ViewModel
+ Some variables still needs to be added (for example reviews, menu positions, events)
+ [BUG] Mentioned in #103 still exists (branch is based on this PR)
> [FEATURE] MichalW RestaurantDetailViewModel

- app/src/main/java/com/example/reservant_mobile/ui/activities/MenuManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/MenuManagementViewModel.kt
> [FEATURE] loading shimmer effect

- app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
Osobiście nie przemawia do mnie koncept tego horizontal scrolla
> [REFACTOR] Input Chips

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/LocationDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantDTO.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
Added button that navigates to RegisterRestaurantActivity in RestaurantManagementActivity:
> [FEATURE] Add restaurant button in RestaurantManagementActivity

- app/src/main/java/com/example/reservant_mobile/ui/activities/MenuItemManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
Merged two MenuItemCards into single one
> [FEATURE] MichalW Single MenuItemCard

- app/src/main/java/com/example/reservant_mobile/data/services/UserService.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/LandingActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MainActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantOwnerProfileActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
> [FEATURE] MaciekM Missing Page

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/fields/FormField.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MenuManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/MenuManagementViewModel.kt
only backend validation for now + loading
todo:
- change menupopup to add photos
- frontend validation
> [FEATURE] menu validation

- app/src/main/java/com/example/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/MapViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
- app/src/main/res/drawable/restaurant_template_icon.xml
- app/src/main/res/drawable/unknown_image.xml
Gdy zdjęcie się załaduje:
Gdy zdjęcie się nie załaduje:
> [REFACTOR] MaciekM mapView

- app/src/main/java/com/example/reservant_mobile/data/models/dtos/OrderDTO.kt
- app/src/main/java/com/example/reservant_mobile/data/utils/BottomNavUtils.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/OrdersActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
- app/src/main/java/com/example/reservant_mobile/ui/navigation/MainRoutes.kt
- app/src/main/java/com/example/reservant_mobile/ui/navigation/RestaurantManagementRoutes.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/OrdersViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
- app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantManagementViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
> [REFACTOR] MaciekM restaurant managment

- app/src/main/java/com/example/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/MenuManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantOwnerProfileActivity.kt
- app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> [FEAUTRE] header

- app/src/main/java/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RegisterActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantOwnerProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/EmployeeComponents.kt
- app/src/main/java/reservant_mobile/ui/components/FormComponents.kt
- app/src/main/java/reservant_mobile/ui/components/MapComponents.kt
- app/src/main/java/reservant_mobile/ui/components/MenuComponents.kt
- app/src/main/java/reservant_mobile/ui/components/MenuItemComponents.kt
- app/src/main/java/reservant_mobile/ui/components/OrderComponents.kt
- app/src/main/java/reservant_mobile/ui/components/ReservationComponents.kt
- app/src/main/java/reservant_mobile/ui/components/RestaurantComponents.kt
- refactored components to different files:
- Components.kt - general purpose components
- FormComponents.kt - components used in forms primarily
- MapComponents.kt - components used by the map activity
- [Employee, Menu, Restaurant etc.]Components.kt - components used to display certain business data
- replaced OutLinedDropdownMenu with ComboBox
- refactored search bar
> [REFACTOR] components

- app/src/androidTest/java/reservant_mobile/services/OrdersServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/RestaurantMenuServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/RestaurantServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/VisitServiceUnitTest.kt
- app/src/main/java/reservant_mobile/data/endpoints/Menus.kt
- app/src/main/java/reservant_mobile/data/endpoints/Orders.kt
- app/src/main/java/reservant_mobile/data/endpoints/Restaurants.kt
- app/src/main/java/reservant_mobile/data/endpoints/User.kt
- app/src/main/java/reservant_mobile/data/endpoints/Visits.kt
- app/src/main/java/reservant_mobile/data/models/dtos/OrderDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/ReviewDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/VisitDTO.kt
- app/src/main/java/reservant_mobile/data/services/OrdersService.kt
- app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
- app/src/main/java/reservant_mobile/data/services/VisitsService.kt
- app/src/main/java/reservant_mobile/ui/components/OrderComponents.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/OrdersViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantManagementViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantViewModel.kt
> [FEATURE] MaciekM order service

- app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
- app/src/main/java/reservant_mobile/data/services/ServicePagingSource.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/MapViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
Dodatkowo wprowadzono drobne poprawki do sps
> [FIX] MaciekM pagination in map

- app/src/main/java/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/MenuItemComponents.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantViewModel.kt
- fixed groups requests in RestaurantManagement
- fixed tags in RegisterRestaurant
> [FIX] requests

- app/src/androidTest/java/reservant_mobile/services/EventServiceUnitTest.kt
- app/src/main/java/reservant_mobile/data/models/dtos/ErrorResponseDTO.kt
- app/src/main/java/reservant_mobile/data/services/EventService.kt
- app/src/main/java/reservant_mobile/data/services/ServiceUtil.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
- ServiceUtil, który parsuje zapytania i error kody z bakendu jeżeli to możliwe
- Aktualizacja obsługi końcówek eventów
> [REFACTOR] MaciekM event service

- app/src/androidTest/java/reservant_mobile/services/FriendsServiceUnitTest.kt
- app/src/main/java/reservant_mobile/data/endpoints/Friends.kt
- app/src/main/java/reservant_mobile/data/models/dtos/FriendRequestDTO.kt
- app/src/main/java/reservant_mobile/data/services/EventService.kt
- app/src/main/java/reservant_mobile/data/services/FriendsService.kt
- app/src/main/java/reservant_mobile/data/services/ServicePagingSource.kt
- app/src/main/java/reservant_mobile/data/services/ServiceUtil.kt
+ Dodatkowe fixy dla sps i service util
> [FEATURE] MaciekM friends service

- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
+ Refactored ProfileActivity to fit other users (add friend, send message, removed edit profile)
[!] Hardcoded - Endpoint missing in backend for fetching other users simple info (name, birthdate etc)
> [FEATURE] MichalW Other users

- app/src/main/java/reservant_mobile/ui/activities/MenuManagementActivity.kt
Wyświetlanie informacji w przypadku nie znalezienia menu (zwrotka z backu 200 OK, ale pusta lista)
> [FEATURE] no menus

- app/src/main/java/reservant_mobile/ui/activities/MenuManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/MenuComponents.kt
Nowy komponent do obsługi zdjęć pobieranych z backendu:
- spinner w trakcie ładowania
- placeholder w przypadku niezaładowania zdjęcia
przykładowa implementacja w **MenuActivity**
> [FEATURE] LoadedPhotoComponent

- app/src/main/java/reservant_mobile/ui/theme/Theme.kt
naprawiłem theme
proszę nie patrz na kod który został zmieniony. generalnie ta zmiana zajęła mi pół roku researchu, od początku marca mnie to irytowało
> [FIX] App theme

- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/RestaurantComponents.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/MapViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
> [FEATURE] MaciekM shopping count + images optimization

- app/src/main/java/reservant_mobile/data/endpoints/Users.kt
- app/src/main/java/reservant_mobile/data/models/dtos/UserSummaryDTO.kt
- app/src/main/java/reservant_mobile/data/services/UserService.kt
- app/src/main/java/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
+ Added support for given actions: 
1. send a friend requests
2. cancel friend request
3. delete friend
4. fetch and view others profile
> [FEATURE] MichalW Add Friends

- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/reservant_mobile/ui/components/RestaurantComponents.kt
Changed EventContent appearance, added EventCard from figma
+ Compatibility with backend after #166 merge
> [FEATURE] MichalW Better EventContent

- app/build.gradle.kts
- app/src/main/java/reservant_mobile/data/constants/PermissionStrings.kt
- app/src/main/java/reservant_mobile/data/models/dtos/EventDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/UserDTO.kt
- app/src/main/java/reservant_mobile/data/services/ServicePagingSource.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/MapComponents.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/MapViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
* search filters
* user location
> [FEATURE] MaciekM map search filters

- app/src/main/java/reservant_mobile/data/utils/BottomNavUtils.kt
- app/src/main/java/reservant_mobile/ui/activities/ChatListActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/EmployeeHomeActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/HomeActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/SettingsActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/SocialActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/TicketHistoryActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/UserComponents.kt
- app/src/main/java/reservant_mobile/ui/navigation/MainRoutes.kt
- app/src/main/java/reservant_mobile/ui/navigation/RestaurantRoutes.kt
- app/src/main/java/reservant_mobile/ui/navigation/UserRoutes.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/SocialViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
- refactored all settings navigation
- changed profilevm loading logic
- removed unnecessary settings
- added social tab
- moved orders to settings
> [FEATURE] Social tab

- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/components/RestaurantComponents.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
+ Added star next to rating
+ Removed Send Message text
+ Refactored Add Friend text - now it changes to Cancel after sending friend request
+ Removed searchbar
+ Fixed Events
+ Changed header to IconWithHeader
+ Added optional action button in IconWithHeader
> [FEATURE] MichalW Profile refactor

- .github/workflows/build.yaml
Jak teraz nie wyjdzie to ide spać
> test MaciekM deploy test

- notify.sh
> [FIX] MaciekM workflow notification script

- app/src/main/java/reservant_mobile/data/utils/Options.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
Teraz chipy wyglądają tak samo i są lepiej zaimplementowane
> [FIX] MaciekM unify chip filters

- app/src/main/java/reservant_mobile/data/models/dtos/EventDTO.kt
- app/src/main/java/reservant_mobile/ui/activities/EventDetailActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/components/FormComponents.kt
- app/src/main/java/reservant_mobile/ui/components/RestaurantComponents.kt
- app/src/main/java/reservant_mobile/ui/navigation/EventRoutes.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/EventViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/MapViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
> [FEATURE] MichalW Event Details

- app/src/main/java/reservant_mobile/ui/activities/OrdersActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/SettingsActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/TicketHistoryActivity.kt
Added missing back buttons from #251 with navigation, fixed padding
> [FIX] Missing back buttons in orders, ticket history

- app/build.gradle.kts
- app/src/main/java/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantStatsActivity.kt
- app/src/main/java/reservant_mobile/ui/navigation/RestaurantManagementRoutes.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantStatsViewmodel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
> [FEATURE] MaciekM stats activity

- app/src/main/java/reservant_mobile/ui/activities/LandingActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/LoginActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RegisterActivity.kt
> [FIX] MaciekM back buttons

- app/src/main/java/reservant_mobile/data/models/dtos/ThreadDTO.kt
- app/src/main/java/reservant_mobile/data/services/ThreadsService.kt
- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/SettingsActivity.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
Resolved issues:
- #275 
- #274 
- #273
> [FIX] Issues

- app/src/main/java/reservant_mobile/ui/viewmodels/MapViewModel.kt
fix #260 
Jakby się pojawiły jeszcze jakieś problemy z tailami:
https://leaflet-extras.github.io/leaflet-providers/preview/
> [FIX] MaciekM map tile

- app/src/main/java/reservant_mobile/data/endpoints/MyRestaurants.kt
- app/src/main/java/reservant_mobile/data/models/dtos/RestaurantDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/TableDTO.kt
- app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
- app/src/main/java/reservant_mobile/ui/activities/EmployeeTablesActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/EmplyeeTablesViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
> [FEATURE] Table functionality

- app/src/main/java/reservant_mobile/data/models/dtos/UserDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/UserSummaryDTO.kt
- app/src/main/java/reservant_mobile/ui/activities/OrderSummaryActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantReservationActivity.kt
- app/src/main/java/reservant_mobile/ui/components/Components.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ReservationViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantManagementViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Added deposits for reservation in RegisterRestaurantActivity (creating and editing)
Fixed profile not loading properly (missing bannedUntil var in dtos)
Added Pay for deposit from client side
Editing restaurant group name
> [FEATURE] Deposit + Profile fix

- app/src/main/java/reservant_mobile/data/models/dtos/EventDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/MessageThreadType.kt
- app/src/main/java/reservant_mobile/data/models/dtos/ThreadDTO.kt
- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
- app/src/main/java/reservant_mobile/ui/activities/SettingsActivity.kt
- app/src/main/java/reservant_mobile/ui/components/RestaurantComponents.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
Fixes:
- fixed EventDTO, which fixes #305 and #300
- fixed ThreadDTO, which fixes #303
- added errorToast message if could not send message to other user
- changed send message button to show only if friendsStatus == Friend
- added Friend Requests in profile (can click on them to see their profile)
Navigation:
- fixed navigation to eventDetailActivity from map and RestaurantDetailActivity #301
- fixed navigation on back button in RestaurantDetailActivity
- fixed navigation to events from profileActivity
> [FIX] Profile, Event Issues

- app/src/androidTest/java/reservant_mobile/services/DeliveryServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/FriendsServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/NominatimServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/RestaurantMenuServiceUnitTest.kt
- app/src/androidTest/java/reservant_mobile/services/RestaurantServiceUnitTest.kt
- app/src/main/java/reservant_mobile/data/endpoints/MyRestaurants.kt
- app/src/main/java/reservant_mobile/data/models/dtos/NominatumDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/ReportDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/RestaurantEmployeeDTO.kt
- app/src/main/java/reservant_mobile/data/models/dtos/RestaurantMenuDTO.kt
- app/src/main/java/reservant_mobile/data/services/APIService.kt
- app/src/main/java/reservant_mobile/data/services/NominatimService.kt
- app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values/strings.xml
dto, które uległy zmianie:
- RestaurantMenuDTO.kt
- ReportDTO
- RestaurantEmployeeDTO.kt
> [FEATURE] nominatim integration + service fix

- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
+ Fixed padding in Friends tab in profileActivity (#337)
> [FIX] ProfileActivity FriendsTab padding fix

- app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> [FIX] padding in friendsTab in ProfileActivity

- app/src/main/java/reservant_mobile/ui/activities/MapActivity.kt
- app/src/main/java/reservant_mobile/ui/viewmodels/MapViewModel.kt
> [FIX] images on mapactivity
